#!/usr/bin/env python3
"""
Daily Digest Automation — Template

Fetches articles from Readwise Reader, generates an AI-powered digest
tailored to your writing style and interests, and delivers it by email
with a published web archive.

Configure via:
  config/writing_guide.md   — writing style and output format
  config/filter_config.json — companies, geographies, sectors, people you care about
  ~/.daily_digest/config.json — API keys and email settings (created by setup.py)
"""

import os
import json
import requests
import anthropic
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import List, Dict, Optional
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
CONFIG_FILE = Path.home() / ".daily_digest" / "config.json"
ARCHIVE_DIR = Path.home() / ".daily_digest" / "archive"
READWISE_API_BASE = "https://readwise.io/api/v3"

# Load user config files from repo
REPO_DIR = Path(__file__).parent
WRITING_GUIDE_FILE = REPO_DIR / "config" / "writing_guide.md"
FILTER_CONFIG_FILE = REPO_DIR / "config" / "filter_config.json"


# ---------------------------------------------------------------------------
# Email HTML template
# ---------------------------------------------------------------------------
EMAIL_HTML_TEMPLATE = '''<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; line-height: 1.7; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
    h1 {{ color: #1a1a1a; border-bottom: 2px solid #e1e4e8; padding-bottom: 10px; margin-bottom: 20px; }}
    h2 {{ color: #24292e; margin-top: 40px; margin-bottom: 16px; border-bottom: 2px solid #888; padding-bottom: 8px; font-size: 1.3em; text-transform: uppercase; letter-spacing: 0.5px; }}
    h3 {{ color: #24292e; margin-top: 28px; margin-bottom: 12px; border-bottom: 1px solid #e1e4e8; padding-bottom: 6px; font-size: 1.1em; }}
    p {{ margin-bottom: 14px; }}
    ul {{ padding-left: 20px; margin-bottom: 16px; }}
    li {{ margin: 16px 0; padding-bottom: 4px; }}
    .header {{ background-color: #f6f8fa; padding: 15px; border-radius: 6px; margin-bottom: 20px; }}
    .citations {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #e1e4e8; }}
    .citations h3 {{ color: #586069; font-size: 0.95em; }}
    .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #e1e4e8; color: #586069; font-size: 0.9em; }}
    strong {{ color: #24292e; }}
    a {{ color: #0366d6; text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
  </style>
</head>
<body>
  <div class="header">
    <h1>{digest_name} — Daily Digest</h1>
    <p><strong>Date:</strong> {date}</p>
    <p><strong>Articles:</strong> {article_count} | <strong>Priority:</strong> {priority_count}</p>
  </div>
  {content}
  <div class="citations">
    <h3>Article Citations ({citation_count} articles)</h3>
    <ul>
{citations}
    </ul>
  </div>
  <div class="footer">
    <p>Generated by Daily Digest automation &bull; <a href="https://read.readwise.io">View in Readwise</a></p>
  </div>
</body>
</html>'''


# ---------------------------------------------------------------------------
# Main class
# ---------------------------------------------------------------------------

class DailyDigest:
    def __init__(self):
        self.config = self._load_config()
        self.readwise_token = self.config.get("readwise_token")
        self.anthropic_api_key = self.config.get("anthropic_api_key")
        self.email_config = self.config.get("email", {})

        ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)

        self.session = requests.Session()
        self.session.headers.update({
            "Accept": "application/json",
            "Authorization": f"Token {self.readwise_token}",
        })
        self.anthropic_client = anthropic.Anthropic(api_key=self.anthropic_api_key)

        # Load writing guide and filter config
        self.writing_guide = self._load_writing_guide()
        self.filter_config = self._load_filter_config()

    # ------------------------------------------------------------------
    # Config loading
    # ------------------------------------------------------------------

    def _load_config(self) -> Dict:
        if not CONFIG_FILE.exists():
            raise FileNotFoundError(
                f"Config not found at {CONFIG_FILE}. Run: python3 setup.py"
            )
        with open(CONFIG_FILE) as f:
            return json.load(f)

    def _load_writing_guide(self) -> str:
        if WRITING_GUIDE_FILE.exists():
            return WRITING_GUIDE_FILE.read_text()
        return "Write clearly, concisely, and analytically. Use specific numbers over vague adjectives."

    def _load_filter_config(self) -> Dict:
        if FILTER_CONFIG_FILE.exists():
            with open(FILTER_CONFIG_FILE) as f:
                return json.load(f)
        return {}

    # ------------------------------------------------------------------
    # Readwise fetching
    # ------------------------------------------------------------------

    def get_recent_documents(self) -> List[Dict]:
        """Fetch documents from Readwise Reader feed and 'later' from last 24 hours."""
        print("Fetching recent documents from Readwise Reader...")
        from dateutil import parser as date_parser

        all_documents = []
        cutoff_time = datetime.now(timezone.utc) - timedelta(hours=24)

        for location in ["feed", "later"]:
            print(f"  Fetching from '{location}'...")
            documents = []
            next_page = None

            try:
                while True:
                    params = {"location": location}
                    if next_page:
                        params["pageCursor"] = next_page

                    response = self.session.get(f"{READWISE_API_BASE}/list/", params=params)

                    if response.status_code == 429:
                        import time
                        wait = int(response.headers.get("Retry-After", 60))
                        print(f"  Rate limited. Waiting {wait}s...")
                        time.sleep(wait)
                        continue

                    response.raise_for_status()
                    data = response.json()

                    for doc in data.get("results", []):
                        doc_date = None
                        for field in ["updated_at", "saved_at", "created_at", "published_date"]:
                            if doc.get(field):
                                try:
                                    doc_date = date_parser.parse(doc[field])
                                    if doc_date.tzinfo is None:
                                        doc_date = doc_date.replace(tzinfo=timezone.utc)
                                    break
                                except Exception:
                                    continue
                        if doc_date is None or doc_date >= cutoff_time:
                            documents.append(doc)

                    next_page = data.get("nextPageCursor")
                    if not next_page:
                        break

            except requests.exceptions.RequestException as e:
                print(f"  Error fetching from '{location}': {e}")
                continue

            print(f"  Found {len(documents)} documents in '{location}'")
            all_documents.extend(documents)

        # Deduplicate
        seen = set()
        unique = []
        for doc in all_documents:
            if doc.get("id") and doc["id"] not in seen:
                seen.add(doc["id"])
                unique.append(doc)

        print(f"Total: {len(unique)} unique documents from last 24 hours")
        return unique

    # ------------------------------------------------------------------
    # Filtering
    # ------------------------------------------------------------------

    def filter_and_mark_documents(self, documents: List[Dict]) -> List[Dict]:
        """Mark documents as priority based on filter_config keywords."""
        priority_sources = self.filter_config.get("priority_sources", [])
        priority_authors = self.filter_config.get("priority_authors", [])

        # Build keyword set from all filter categories
        all_keywords: List[str] = []
        for category in ["portfolio_companies", "geographies", "people", "industries_sectors", "themes"]:
            for entry in self.filter_config.get(category, []):
                all_keywords.extend(entry.get("keywords", []))

        for doc in documents:
            doc["is_priority"] = False

            source = doc.get("source_url", "").lower()
            if any(s.lower() in source for s in priority_sources):
                doc["is_priority"] = True

            author = (doc.get("author") or "").lower()
            if any(a.lower() in author for a in priority_authors):
                doc["is_priority"] = True

            text = (
                (doc.get("title") or "") + " " +
                (doc.get("summary") or "") + " " +
                (doc.get("author") or "")
            ).lower()
            if any(kw.lower() in text for kw in all_keywords):
                doc["is_priority"] = True

        return documents

    # ------------------------------------------------------------------
    # Prompt construction
    # ------------------------------------------------------------------

    def _build_filter_context(self) -> str:
        """Convert filter_config into a structured context block for the prompt."""
        fc = self.filter_config
        lines = []

        digest_name = fc.get("digest_name", "My Digest")
        author = fc.get("author_name", "the reader")
        focus = fc.get("focus_description", "")
        lines.append(f"DIGEST: {digest_name}")
        lines.append(f"AUTHOR: {author}")
        if focus:
            lines.append(f"FOCUS: {focus}")
        lines.append("")

        # Portfolio companies
        companies = fc.get("portfolio_companies", [])
        if companies:
            lines.append("PORTFOLIO / KEY ENTITIES:")
            for c in companies:
                if c.get("name") and c["name"] != "Company Name":
                    desc = c.get("description", "")
                    kw = ", ".join(c.get("keywords", []))
                    lines.append(f"  • {c['name']}: {desc} [keywords: {kw}]")
            lines.append("")

        # Geographies
        geos = fc.get("geographies", [])
        if geos:
            lines.append("GEOGRAPHIES OF INTEREST:")
            for g in geos:
                if g.get("name"):
                    kw = ", ".join(g.get("keywords", []))
                    lines.append(f"  • {g['name']}: {g.get('why_relevant','')} [keywords: {kw}]")
            lines.append("")

        # Industries
        industries = fc.get("industries_sectors", [])
        if industries:
            lines.append("INDUSTRIES / SECTORS OF INTEREST:")
            for i in industries:
                if i.get("name"):
                    kw = ", ".join(i.get("keywords", []))
                    lines.append(f"  • {i['name']}: {i.get('why_relevant','')} [keywords: {kw}]")
            lines.append("")

        # Themes
        themes = fc.get("themes", [])
        if themes:
            lines.append("MACRO THEMES:")
            for t in themes:
                if t.get("name"):
                    kw = ", ".join(t.get("keywords", []))
                    lines.append(f"  • {t['name']}: {t.get('why_relevant','')} [keywords: {kw}]")
            lines.append("")

        # People
        people = fc.get("people", [])
        if people:
            lines.append("PEOPLE TO TRACK:")
            for p in people:
                if p.get("name"):
                    lines.append(f"  • {p['name']} ({p.get('role','')}): {p.get('why_relevant','')}")
            lines.append("")

        return "\n".join(lines)

    def _build_section_template(self) -> str:
        """Build section instructions from writing_guide.md."""
        fc = self.filter_config
        digest_name = fc.get("digest_name", "My Digest")
        focus = fc.get("focus_description", "your focus area")

        has_companies = bool([
            c for c in fc.get("portfolio_companies", [])
            if c.get("name") and c["name"] != "Company Name"
        ])

        sections = f"""
OUTPUT SECTIONS (use HTML formatting for email):

<h2>Key Developments</h2>
3-5 major developments from today's articles. Each must follow this structure:
1. <strong>Bold title</strong> summarizing the key takeaway
2. 3-5 <ul><li> bullet points — one analytical sentence each. Bold key numbers and entity names. Include inline article links: <a href="https://read.readwise.io/read/ARTICLE_ID">descriptive text</a>
3. <em>Counter: one sentence naming the main risk or alternative reading.</em>

<h2>Cross-Article Patterns</h2>
2-3 structural patterns synthesized across multiple articles. Distinct from Key Developments — these are connections not obvious from any single piece.

{"<h2>" + digest_name + " Relevance</h2>" + chr(10) + "Connect today's news directly to entities in the filter config above (portfolio companies, geographies, sectors, people). One bullet per connection. Format: <strong>[Entity Name]</strong>: one sentence + inline article link. Only include genuine, direct connections — do not force relevance." if has_companies else ""}

<h2>Other Sections</h2>
Include any additional sections defined in the writing guide that have relevant content today. Skip sections with no relevant content and state why briefly.
"""
        return sections

    # ------------------------------------------------------------------
    # Generation
    # ------------------------------------------------------------------

    def generate_synopsis(self, documents: List[Dict], historical: List[Dict]) -> Dict:
        """Generate AI digest using Claude."""
        print("Generating digest with Claude...")

        today = datetime.now()
        is_weekly_day = today.weekday() == 0  # Monday

        doc_summaries = [
            {
                "id": doc.get("id", ""),
                "title": doc.get("title", "Untitled"),
                "author": doc.get("author", "Unknown"),
                "source": doc.get("source_url", ""),
                "summary": doc.get("summary", ""),
                "published_date": doc.get("published_date", ""),
                "is_priority": doc.get("is_priority", False),
            }
            for doc in documents
        ]
        priority_docs = [d for d in doc_summaries if d["is_priority"]]

        # Historical context
        historical_summary = ""
        if historical:
            historical_summary = "PREVIOUS SYNOPSES (last 7 days — for pattern continuity, not repetition):\n\n"
            for i, h in enumerate(historical, 1):
                themes = h.get("key_themes", [])
                historical_summary += f"  Day -{i} ({h.get('date','')}): {', '.join(themes[:3])}\n"

        # Weekly section
        weekly_section = ""
        if is_weekly_day:
            weekly_section = """
<h2>Weekly Pattern Analysis</h2>
Synthesize the FULL WEEK — not just today. Draw from the historical synopses. Do NOT repeat insights already covered in today's daily sections.

Identify 3 patterns from this week that represent structural changes, not cyclical noise. Each: bold title → 3-5 bullets with specific data points → the hard questions that remain open.

What changed this week that matters in 5 years?
"""

        filter_context = self._build_filter_context()
        section_template = self._build_section_template()

        prompt = f"""You are generating a personalized daily intelligence digest.

{filter_context}

WRITING GUIDE:
{self.writing_guide}

Today's date: {today.strftime('%Y-%m-%d')}
You have {len(documents)} articles from the last 24 hours.

PRIORITY ARTICLES (matching user's interests):
{json.dumps(priority_docs[:15], indent=2) if priority_docs else "None"}

ALL ARTICLES:
{json.dumps(doc_summaries[:60], indent=2)}

{historical_summary}

{section_template}

{weekly_section}

CRITICAL RULES:
- Each insight appears ONCE in the most relevant section. Do not restate across sections.
- Bold all key numbers (<strong>42%</strong>) and entity names (<strong>Company Name</strong>).
- Every bullet referencing an article MUST include an inline link: <a href="https://read.readwise.io/read/ARTICLE_ID">anchor text</a>
- Numbers over adjectives — every vague claim earns its place with evidence.
- Assume the reader has deep domain knowledge. Skip basics.
- Use generous HTML spacing between elements.
"""

        try:
            message = self.anthropic_client.messages.create(
                model="claude-sonnet-4-6",
                max_tokens=8000,
                messages=[{"role": "user", "content": prompt}],
            )
            synopsis_text = message.content[0].text
        except Exception as e:
            print(f"Error generating synopsis: {e}")
            synopsis_text = f"Error generating synopsis: {e}"

        return {
            "date": today.strftime("%Y-%m-%d"),
            "document_count": len(documents),
            "priority_count": len(priority_docs),
            "synopsis": synopsis_text,
            "key_themes": self._extract_themes(synopsis_text),
            "is_weekly_report": is_weekly_day,
            "documents": doc_summaries,
        }

    def _extract_themes(self, synopsis_text: str) -> List[str]:
        themes = []
        for line in synopsis_text.split("\n"):
            line = line.strip()
            if line.startswith(("-", "•")):
                theme = line.lstrip("-•").strip().split(".")[0][:50]
                if theme:
                    themes.append(theme)
            elif line.startswith("**") and line.endswith("**"):
                theme = line.strip("*").strip()[:50]
                if theme:
                    themes.append(theme)
        return themes[:5]

    # ------------------------------------------------------------------
    # Archive
    # ------------------------------------------------------------------

    def get_historical_synopses(self, days: int = 7) -> List[Dict]:
        historical = []
        for i in range(1, days + 1):
            date = datetime.now() - timedelta(days=i)
            filename = ARCHIVE_DIR / f"synopsis_{date.strftime('%Y%m%d')}.json"
            if filename.exists():
                with open(filename) as f:
                    historical.append(json.load(f))
        return historical

    def save_synopsis(self, synopsis: Dict) -> None:
        today = datetime.now()
        filename = ARCHIVE_DIR / f"synopsis_{today.strftime('%Y%m%d')}.json"
        with open(filename, "w") as f:
            json.dump(synopsis, f, indent=2)
        print(f"Archived to {filename}")

    # ------------------------------------------------------------------
    # Site update
    # ------------------------------------------------------------------

    def update_site_data(self) -> None:
        """Rebuild digests.json, commit, and push to trigger Netlify deploy."""
        import subprocess

        print("Updating site data...")
        from build_site import load_synopses, build_digests_json

        synopses = load_synopses(ARCHIVE_DIR)
        if not synopses:
            print("No synopses found. Skipping site update.")
            return

        output_dir = REPO_DIR / "site" / "data"
        build_digests_json(synopses, output_dir)

        commit_msg = f"Update digest data — {datetime.now().strftime('%Y-%m-%d')}"
        try:
            subprocess.run(["git", "add", "site/data/digests.json"], cwd=REPO_DIR, check=True, capture_output=True)
            result = subprocess.run(["git", "diff", "--cached", "--quiet"], cwd=REPO_DIR, capture_output=True)
            if result.returncode == 0:
                print("No changes. Skipping push.")
                return
            subprocess.run(["git", "commit", "-m", commit_msg], cwd=REPO_DIR, check=True, capture_output=True)
            subprocess.run(["git", "push", "origin", "main"], cwd=REPO_DIR, check=True, capture_output=True, timeout=60)
            print("Pushed to GitHub. Netlify will auto-deploy.")
        except subprocess.CalledProcessError as e:
            print(f"Git error: {e.stderr[:300] if e.stderr else e}")
        except subprocess.TimeoutExpired:
            print("Git push timed out.")

    # ------------------------------------------------------------------
    # Email
    # ------------------------------------------------------------------

    def send_email(self, synopsis: Dict) -> None:
        print("Sending email...")

        digest_name = self.filter_config.get("digest_name", "Daily Digest")
        subject = f"{digest_name} — {synopsis['date']}"
        if synopsis.get("is_weekly_report"):
            subject = f"{digest_name} — Weekly Analysis — {synopsis['date']}"

        citations = []
        for doc in synopsis.get("documents", [])[:50]:
            title = doc.get("title", "Untitled")
            doc_id = doc.get("id", "")
            url = f"https://read.readwise.io/read/{doc_id}" if doc_id else doc.get("source", "#")
            citations.append(f'<li><a href="{url}">{title}</a></li>')

        html_body = EMAIL_HTML_TEMPLATE.format(
            digest_name=digest_name,
            date=synopsis["date"],
            article_count=synopsis["document_count"],
            priority_count=synopsis["priority_count"],
            content=synopsis["synopsis"],
            citation_count=len(citations),
            citations="\n".join(citations) if citations else "<li>No articles</li>",
        )

        plain_text = (
            f"{digest_name} — {synopsis['date']}\n"
            f"Articles: {synopsis['document_count']} | Priority: {synopsis['priority_count']}\n\n"
            f"{synopsis['synopsis']}\n\n---\nGenerated by Daily Digest automation"
        )

        smtp_server = self.email_config.get("smtp_server", "smtp.gmail.com")
        smtp_port = self.email_config.get("smtp_port", 587)
        sender_email = self.email_config.get("sender_email")
        sender_password = self.email_config.get("sender_password")
        recipient_email = self.email_config.get("recipient_email")

        if not all([sender_email, sender_password, recipient_email]):
            print("Email config incomplete. Skipping send. Synopsis saved to archive.")
            return

        try:
            msg = MIMEMultipart("alternative")
            msg["From"] = sender_email
            msg["To"] = recipient_email
            msg["Subject"] = subject
            msg.attach(MIMEText(plain_text, "plain"))
            msg.attach(MIMEText(html_body, "html"))

            with smtplib.SMTP(smtp_server, smtp_port) as server:
                server.starttls()
                server.login(sender_email, sender_password)
                server.send_message(msg)

            print(f"Email sent to {recipient_email}")
        except Exception as e:
            print(f"Email error: {e}. Synopsis saved to archive.")

    # ------------------------------------------------------------------
    # Mark as seen
    # ------------------------------------------------------------------

    def mark_as_seen(self, document_ids: List[str]) -> None:
        import time
        print(f"Marking {len(document_ids)} documents as seen...")
        for doc_id in document_ids:
            try:
                response = self.session.patch(
                    f"{READWISE_API_BASE}/save/",
                    json={"id": doc_id, "location": "archive"},
                )
                if response.status_code == 429:
                    time.sleep(int(response.headers.get("Retry-After", 60)))
                    continue
                response.raise_for_status()
            except requests.exceptions.RequestException as e:
                print(f"Error marking {doc_id}: {e}")

    # ------------------------------------------------------------------
    # Main run
    # ------------------------------------------------------------------

    def run(self) -> None:
        print("=" * 60)
        print(f"Daily Digest — {self.filter_config.get('digest_name', 'My Digest')}")
        print(f"Running at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print("=" * 60)

        documents = self.get_recent_documents()
        if not documents:
            print("No documents found in the last 24 hours. Exiting.")
            return

        documents = self.filter_and_mark_documents(documents)
        historical = self.get_historical_synopses(days=7)
        synopsis = self.generate_synopsis(documents, historical)
        self.save_synopsis(synopsis)
        self.update_site_data()
        self.send_email(synopsis)

        feed_ids = [d.get("id") for d in documents if d.get("id") and d.get("location") == "feed"]
        if feed_ids:
            self.mark_as_seen(feed_ids)

        print("=" * 60)
        print("Digest completed successfully")
        print("=" * 60)


def main():
    try:
        DailyDigest().run()
    except Exception as e:
        print(f"Fatal error: {e}")
        raise


if __name__ == "__main__":
    main()
